{% set name = "vdt" %}
{% set version = "0.4.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/dpiparo/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 643136a38d6890c1cf18074bd494f99a4f269429ac552c57907e28c0091df8e6

build:
  number: 1002
  skip: True  # [win]
  run_exports:
    - {{ pin_subpackage('vdt', max_pin='x.x.x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
  host:
  run:

test:
  # Some package might need a `test/commands` key to check CLI.
  # List all the packages/modules that `run_test.py` imports.
  imports:

about:
  home: https://svnweb.cern.ch/trac/vdt
  license: GPL-3.0
  license_family: GPL
  license_file: Licence.txt
  summary: 'VectoriseD maTh C++ Library for Fast Math'

  description: |
    VDT is a library of mathematical functions, implemented in double and
    single precision. The implementation is fast and with the aid of modern
    compilers (e.g. gcc 4.7) autovectorisable.
  dev_url: https://github.com/dpiparo/vdt

extra:
  recipe-maintainers:
    - chrisburr
