travis:
  secure:
    BINSTAR_TOKEN: Qlor+FoaT34ZSdaeTOWfxCeBWvoIVkyhXSkOF1WBFgesQBZ7RunhxLoWRRkTmB+C+9BQuH9/VcHUqgGreaEjDVKf+30oJhzTMIcWkKGK0EGuzJxOC0sJUKPCz46/C2sKRavEGs5npInEHEtT2FkMVyg3pQwc5i2757T4PZoDkC0BsJgPCCtosgYh6ETJ/JRMg8pzZZ3ord5VHWA6bZ63DeazlCsPxXu/92aESQoLFSOkl2TBIg8RXfT3WHn8ZUhONE10iU/DbAscvscSDwjsYxM98UMvClI2gr50CHuxFY9vsbtXPgjC0l6A4OxXtSVPLWhkwckSwfPIKI0SzRIW9AmK0CUAzEkVG5xRDufs6dYRBqq2lmwCiRX6P3XZdjtf2OCMd0q4rBvInFEuyM99bca9E01YPKjkgHxdiJmAYpc+37bjYMPTMm9L6ggzgQAhqR6ywACicWUkvryTcX+xmtIDqeTlERH1OFtI9NxboHI5HXPUk6fKp3qlU229Gmpst5fobyE+wkSYlfywsU0RlbPxmiW2fq+jWIa6S1Hi6ek3XQIZbkSUQ5DHUEd3ODWylmRTqcndKm4J662rzXp6bzWw8S7eruVMVKTVnn0eJsSnaK5kWF9nB2GDG0reRTJ+qFPKbSK4sXyZk4hevIn3mKnV/WwlW+9ZnEHGhTdWftI=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
